In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
import sqlite3

In [2]:
conn=sqlite3.connect('customer_churn.db')

sql_query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

tables=pd.read_sql(sql_query,conn)

for table_name in tables['name']:
    df=pd.read_sql(f"SELECT * FROM {table_name}",conn)
    globals()[f"df_{table_name}"]=df
    print(f"created dataframe : df{table_name}")

conn.close()

created dataframe : dfdb_customer
created dataframe : dfdb_subscription
created dataframe : dfdb_support

In [3]:
conn = sqlite3.connect('customer_churn.db') 

for table in tables['name']:
    print(f"\n Table_Name: {table_name}")

    columns_query=f"PRAGMA table_info({table_name})"
    columns=pd.read_sql(columns_query,conn)
    print("Columns:")
    print(columns['name'].tolist())

conn.close()

 Table_Name: db_support
Columns:
['customerid', 'complaint_date', 'escalations', 'csat_score', 'col_1', 'comment']

 Table_Name: db_support
Columns:
['customerid', 'complaint_date', 'escalations', 'csat_score', 'col_1', 'comment']

 Table_Name: db_support
Columns:
['customerid', 'complaint_date', 'escalations', 'csat_score', 'col_1', 'comment']

In [4]:
df_db_customer.head()

,customerid,name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00,travel,None
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00,None,None
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00,movie,None
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00,None,None
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00,drama,None

In [5]:
df_db_customer.tail()

,customerid,name,country,state,gender,dob,interests,pincode
16,0020-JDNXP,rikim,India,Meghalaya,Female,1994-08-19 00:00:00,None,None
17,0021-IKXGC,vishakha,India,Rajasthan,Female,2000-09-02 00:00:00,None,None
18,0022-TCJCI,raghvendra,India,Telangana,Male,1983-12-30 00:00:00,None,None
19,0023-HGHWL,rishabh,India,Uttar Pradesh,Men,1991-05-14 00:00:00,None,None
20,0023-UYUPN,sudevi,India,Maharashtra,Women,1977-10-06 00:00:00,None,None

In [6]:
df_db_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerid  21 non-null     object
 1   name        21 non-null     object
 2   country     18 non-null     object
 3   state       21 non-null     object
 4   gender      21 non-null     object
 5   dob         21 non-null     object
 6   interests   4 non-null      object
 7   pincode     0 non-null      object
dtypes: object(8)
memory usage: 1.4+ KB

In [7]:
df_db_customer.rename(columns={'name':'customer_name'},inplace=True)
df_db_customer.head()

,customerid,customer_name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00,travel,None
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00,None,None
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00,movie,None
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00,None,None
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00,drama,None

In [8]:
df_db_customer.drop(columns=['pincode','interests'],inplace=True)
df_db_customer.tail()

,customerid,customer_name,country,state,gender,dob
16,0020-JDNXP,rikim,India,Meghalaya,Female,1994-08-19 00:00:00
17,0021-IKXGC,vishakha,India,Rajasthan,Female,2000-09-02 00:00:00
18,0022-TCJCI,raghvendra,India,Telangana,Male,1983-12-30 00:00:00
19,0023-HGHWL,rishabh,India,Uttar Pradesh,Men,1991-05-14 00:00:00
20,0023-UYUPN,sudevi,India,Maharashtra,Women,1977-10-06 00:00:00

In [9]:
df_db_customer['dob']=pd.to_datetime(df_db_customer['dob'])
df_db_customer.head()

   customerid customer_name country        state  gender        dob
0  0002-ORFBO        keshav   India  Maharashtra    Male 1982-04-12
1  0003-MKNFE        raghav   India    Karnataka    Male 1995-11-23
2  0004-TLHLJ        lalita   India        Delhi  Female 1978-02-15
3  0011-IGKFF         mohan   India     Nagaland    Male 2001-08-30
4  0013-EXCHZ          mira   India        Delhi  Female 1990-05-05

In [11]:
df_db_customer['gender']=df_db_customer['gender'].replace({'Men':'Male','Women':'Female'})

In [13]:
df_db_customer['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [15]:
df_db_customer['country'].isna().sum()

np.int64(3)

In [17]:
df_db_customer[df_db_customer['country'].isna()]

    customerid customer_name country      state  gender        dob
5   0013-MHZWF         durga    None      Delhi  Female 1988-12-10
8   0015-UOCOJ          maya    None  Kathmandu  Female 1985-07-07
12  0018-NYROU        chitra    None  Telangana  Female 2004-12-01