In [37]:
import numpy as np 
import pandas as pd

In [38]:
# Creating DataFrame using dictonary
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [39]:
df.shape

(4, 4)

In [40]:
# Creating DataFrame using list and then adding header-columns
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [41]:
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selection and Indexing of Columns

In [42]:
df2[['Name','Salary']]

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

In [43]:
df2['designation']=['doc','er.','er.',"doc"]
df2

    Name  Age      City  Salary designation
0   John   28  New York   65000         doc
1   Anna   34     Paris   70000         er.
2  Peter   29    Berlin   62000         er.
3  Linda   42    London   85000         doc

In [44]:
# Removing Columns
df2.drop(['designation'],axis=1,inplace=True)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2.loc[[0,2]] #By Indexing

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000

In [ ]:
df2.loc[:1] # By Slicing

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [ ]:
df2.iloc[1:3] #Slicing by Indexing

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000

Selecting Subsets of Rows and Columns

In [60]:
df.loc[[0,1]][["Age","Salary"]]

   Age  Salary
0   28   65000
1   34   70000

In [65]:
df.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

Conditional Selection

In [ ]:
df[df2['Age']>30] ##I only want to see those people whose age is above 30

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
df[(df2['Age']>30) & (df2['City']=='Paris')] ##I only want poeple whose age is above 30 and their city must be paris

   Name  Age   City  Salary
1  Anna   34  Paris   70000